export const INITIAL_ASSET_TEMPLATES: any[] = [
  {
    id: "TI-001",
    category: "Servidor",
    brand: "Dell",
    model: "PowerEdge R750",
    serialNumber: "DELL-SRV-9012",
    ipAddress: "192.168.4.10",
    macAddress: "00:15:5D:01:A2:03",
    status: "Operativo",
    specification: "Dual Xeon Gold, 256GB RAM, 8TB SAS RAID-10",
    purchaseDate: "2024-02-15",
    cargo: "Administrador de Sistemas TI",
    responsable: "Ing. Alejandro Valenzuela",
    ubicacion: "Data Center - Rack B3",
    software: [
      { name: "Windows Server 2022 Standard", version: "21H2", licensed: true, licenseType: "Comercial/Licencia Activa", licenseKey: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX" },
      { name: "Microsoft SQL Server 2019 Enterprise", version: "15.0", licensed: true, licenseType: "Suscripción Corp", licenseKey: "SQL-XXXXX-XXXXX" },
      { name: "Veeam Backup & Replication", version: "v12", licensed: true, licenseType: "Suscripción Corp", licenseKey: "VEEM-XXXXX-XXXXX" },
      { name: "Docker Community Edition", version: "24.0.7", licensed: true, licenseType: "Libre/Gratuito" }
    ]
  },
  {
    id: "TI-002",
    category: "Computador",
    brand: "Advantech",
    model: "ARK-3530 Rugged Box PC",
    serialNumber: "ADV-IND-4412",
    ipAddress: "10.20.1.45",
    macAddress: "00:07:32:DE:F1:23",
    status: "Operativo",
    specification: "Intel Core i7 Gen 10, 32GB RAM, Dual LAN, IP40 Rugged",
    purchaseDate: "2023-11-20",
    cargo: "Jefe de Patio de Contenedores",
    responsable: "Ramón Espinoza",
    ubicacion: "Torre de Control - Puerta Norte",
    software: [
      { name: "Windows 10 IoT Enterprise", version: "21H2 LTSC", licensed: true, licenseType: "OEM/Bios" },
      { name: "SCADA InduSoft Web Studio", version: "v8.1", licensed: true, licenseType: "Comercial/Licencia Activa", licenseKey: "IND-XXXXX-XXXXX" },
      { name: "AnyDesk Remote Desktop", version: "7.1.13", licensed: false, licenseType: "Sin Licenciar/Demo" }
    ]
  },
  {
    id: "TI-003",
    category: "Portátil",
    brand: "Lenovo",
    model: "ThinkPad T14 Gen 4",
    serialNumber: "LNV-THK-8854",
    ipAddress: "10.20.5.112",
    macAddress: "F8:E4:E3:A2:B1:00",
    status: "Operativo",
    specification: "Intel i7, 16GB RAM, 512GB SSD NVMe, LTE Module",
    purchaseDate: "2025-01-10",
    cargo: "",
    responsable: "",
    ubicacion: ""
  },
  {
    id: "TI-004",
    category: "Redes",
    brand: "Cisco",
    model: "Catalyst IE3400 Industrial",
    serialNumber: "CSCO-SW-0322",
    ipAddress: "10.20.40.1",
    macAddress: "A4:93:3F:88:99:CE",
    status: "Operativo",
    specification: "Managed 24-Port GbE PoE+, Rugged DIN Rail Mount",
    purchaseDate: "2024-05-18",
    cargo: "N/A - Planta Eléctrica",
    responsable: "Dpto. Redes y Conectividad",
    ubicacion: "Caseta de Distribución 2A"
  },
  {
    id: "TI-005",
    category: "Portátil",
    brand: "Dell",
    model: "Latitude 5430 Rugged",
    serialNumber: "DELL-RGD-7140",
    ipAddress: "10.20.5.155",
    macAddress: "28:F1:0E:99:8A:2F",
    status: "En Mantenimiento",
    specification: "Intel i5, 16GB DDR4, Pantalla Alto Brillo IP53",
    purchaseDate: "2024-08-05",
    cargo: "Técnico Inspector de Muelles",
    responsable: "Eduardo Arancibia",
    ubicacion: "Oficina de Operaciones Marítimas"
  },
  {
    id: "TI-006",
    category: "Impresora",
    brand: "Zebra",
    model: "ZT411 Thermal Industrial",
    serialNumber: "ZEB-PRN-5412",
    ipAddress: "10.20.50.8",
    macAddress: "00:07:4D:43:21:BA",
    status: "Operativo",
    specification: "Impresora de etiquetas Industrial, Transferencia Térmica 300dpi",
    purchaseDate: "2023-06-12",
    cargo: "",
    responsable: "",
    ubicacion: ""
  },
  {
    id: "TI-007",
    category: "Computador",
    brand: "Hatteland Technology",
    model: "Maritime Panel Computer 24\"",
    serialNumber: "HAT-NAV-1189",
    ipAddress: "172.16.100.41",
    macAddress: "4C:D1:A1:22:B8:3F",
    status: "Operativo",
    specification: "Intel Core i5, Pantalla Legible Solar Marine, Alimentación Redundante",
    purchaseDate: "2022-09-30",
    cargo: "Capitán del Remolcador",
    responsable: "Carlos Mendoza",
    ubicacion: "Puente de Mando - Remolcador 'Tornado II'"
  },
  {
    id: "TI-008",
    category: "Monitoreo / Seguridad",
    brand: "Hikvision",
    model: "PTZ Dome DS-2DF8",
    serialNumber: "HKV-CAM-8890",
    ipAddress: "192.168.10.45",
    macAddress: "70:B1:E3:44:55:66",
    status: "Operativo",
    specification: "Cámara PTZ Industrial Laser, 4K Zoom 40x, Exterior Clima Extremo",
    purchaseDate: "2024-10-02",
    cargo: "Operador de CCTV",
    responsable: "Guardia Turno Nocturno",
    ubicacion: "Muelle de Combustible - Poste 4"
  },
  {
    id: "TI-009",
    category: "Servidor",
    brand: "Lenovo",
    model: "ThinkSystem ST250",
    serialNumber: "LNV-SRV-2234",
    ipAddress: "192.168.4.15",
    macAddress: "E0:4F:43:BB:CC:90",
    status: "En Stock",
    specification: "Xeon E-2300, 32GB RAM, 2x 2TB HDD Hot-Swap SATA",
    purchaseDate: "2025-03-01",
    cargo: "",
    responsable: "",
    ubicacion: ""
  },
  {
    id: "TI-010",
    category: "Computador",
    brand: "HP",
    model: "Z2 G9 Workstation",
    serialNumber: "HP-WRK-0012",
    ipAddress: "10.20.2.14",
    macAddress: "CC:25:D9:E0:AA:BB",
    status: "Operativo",
    specification: "Intel Core i9, 64GB DDR5, NVIDIA RTX A4000, 1TB SSD",
    purchaseDate: "2024-12-15",
    cargo: "Analista de Logística y Rutas",
    responsable: "Sofía Martínez",
    ubicacion: "Segundo Piso - Oficina Despacho Marítimo",
    software: [
      { name: "Windows 11 Pro Corp", version: "23H2", licensed: true, licenseType: "Comercial/Licencia Activa", licenseKey: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX" },
      { name: "Microsoft Office 365 ProPlus", version: "v16.0", licensed: true, licenseType: "Suscripción Corp", licenseKey: "O365-XXXXX-XXXXX" },
      { name: "AutoCAD Map 3D 2024", version: "2024.1", licensed: true, licenseType: "Comercial/Licencia Activa", licenseKey: "ACAD-XXXXX-XXXXX" },
      { name: "Sincronizador NavisLog", version: "v4.2.1", licensed: true, licenseType: "OEM/Bios" },
      { name: "WinRAR Compress Utility", version: "6.22", licensed: false, licenseType: "Sin Licenciar/Demo" }
    ]
  },
  {
    id: "TI-011",
    category: "Otro",
    brand: "Getac",
    model: "UX10 Rugged Tablet",
    serialNumber: "GTC-TBL-7711",
    ipAddress: "10.20.5.190",
    macAddress: "FC:E8:06:55:FF:44",
    status: "Dado de Baja",
    specification: "Intel i5, 8GB RAM, 256GB SSD, GPS, 1000 nits, IP65 - Daño de Pantalla",
    purchaseDate: "2021-04-10",
    cargo: "Supervisor de Tolvas",
    responsable: "Héctor Tapia",
    ubicacion: "Bodega de Resguardo Técnico"
  },
  {
    id: "TI-012",
    category: "Redes",
    brand: "Fortinet",
    model: "FortiGate 100F",
    serialNumber: "FTNT-FW-8012",
    ipAddress: "192.168.1.1",
    macAddress: "04:D5:90:3A:4E:5F",
    status: "Operativo",
    specification: "Enterprise SDN Firewall, Unified Threat Management Interface",
    purchaseDate: "2023-01-20",
    cargo: "Administrador de Redes",
    responsable: "Área de Soporte de Infraestructura",
    ubicacion: "Rack de Comunicaciones - Oficina Principal"
  }
];
